version: 2.1
jobs:
  check-whitespace:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Check for trailing whitespace
          command: dev-scripts/check-trailing-whitespace
  check_html_format:
    docker:
      - image: cimg/node:20.9.0
    steps:
      - checkout
      - run:
          name: Download npm packages
          command: npm install
      - run:
          name: Check formatting
          command: npm run check-format
  build:
    docker:
      - image: peaceiris/hugo:v0.109.0
    steps:
      - checkout
      - run:
          name: Build public site
          command: hugo version && hugo --minify
      - persist_to_workspace:
          root: ./
          paths:
            - public
            - netlify.toml
  deploy:
    docker:
      - image: cimg/node:20.9.0
    environment:
      NETLIFY_SITE_ID: c5ddb255-01d9-4742-81c7-44415b9b587e
    resource_class: small
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install netlify CLI
          command: npm install netlify-cli
      - run:
          name: Deploy to production
          command: |
            ./node_modules/.bin/netlify \
              deploy \
              --dir=public \
              --auth "${NETLIFY_AUTH_TOKEN}" \
              --site="${NETLIFY_SITE_ID}" \
              --prod
workflows:
  version: 2
  test-deploy:
    jobs:
      - check-whitespace
      - check_html_format
      - build
      - deploy:
          requires:
            - build
            - check-whitespace
            - check_html_format
          filters:
            branches:
              only: master
