version: 2.1
jobs:
  check-whitespace:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Check for trailing whitespace
          command: build-checks/check-trailing-whitespace
  build:
    docker:
      - image: peaceiris/hugo:v0.84.4
    steps:
      - checkout
      - run:
          name: Get submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Build public site
          command: hugo
      - persist_to_workspace:
          root: ./
          paths:
            - public
            - firebase.json
            - .firebaserc
  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install firebase-tools
          command: npm install firebase-tools
      - run:
          name: Deploy to firebase
          command: |
            ./node_modules/.bin/firebase deploy --token="$FIREBASE_DEPLOY_TOKEN"
workflows:
  version: 2
  test-deploy:
    jobs:
      - check-whitespace
      - build
      - deploy:
          requires:
            - build
            - check-whitespace
          filters:
            branches:
              only: master
