defaults: &defaults
  working_directory: ~/repo
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.4.4
    environment:
      BUNDLE_PATH: ~/repo/_vendor/bundle
    steps:
      - checkout
      - restore_cache:
          keys:
            - rubygems-{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ checksum "Gemfile.lock" }}
            - rubygems-{{ .Environment.CIRCLE_CACHE_VERSION }}
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rubygems-{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ checksum "Gemfile.lock" }}
          paths:
            - "{{ .Environment.BUNDLE_PATH }}"
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - persist_to_workspace:
          root: ./
          paths:
            - _site
            - firebase.json
            - .firebaserc
  deploy:
    <<: *defaults
    docker:
      - image: circleci/node:8.12
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install firebase-tools
          command: npm install firebase-tools
      - run:
          name: Deploy to firebase
          command: |
            ./node_modules/.bin/firebase deploy --token="$FIREBASE_DEPLOY_TOKEN"
workflows:
  version: 2
  test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
