version: 2.1
jobs:
  check-whitespace:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - run:
          name: Check for trailing whitespace
          command: build-checks/check-trailing-whitespace
  build:
    docker:
      - image: mtlynch/gatsby:2.5.4-node10
    steps:
      - checkout
      - run:
          name: Gatsby build
          command: gatsby build
      - persist_to_workspace:
          root: ./
          paths:
            - public
            - firebase.json
            - .firebaserc
  deploy:
    docker:
      - image: circleci/node:8.12
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Install firebase-tools
          command: npm install firebase-tools
      - run:
          name: Deploy to firebase
          command: |
            ./node_modules/.bin/firebase deploy --token="$FIREBASE_DEPLOY_TOKEN"
workflows:
  version: 2
  test-deploy:
    jobs:
      - check-whitespace
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
