#!/bin/bash

# Exit on first failing command.
set -e
# Echo commands to console.
set -x
# Exit on unset variable.
set -u

# Execute Markdown Linter
bundler exec mdl \
  _pages \
  _posts \
  --style _linter/markdown-linter-style.rb
