#!/bin/bash

# Echo commands to console.
set -x
# Exit on first failing command.
set -e
# Exit on unset variable.
set -u

# Execute Markdown Linter
bundler exec mdl $(find -name "*.md" -not -path "./_vendor/*") \
  --style _linter/markdown-linter-style.rb
