#!/usr/bin/env bash

set -eux

INPUT=$1
EPISODE_NUMBER=$2
MOVIE_TITLE=$3

# Find the episode directory and construct output path
OUTPUT_FILE=$(ls -d "./content/post/${EPISODE_NUMBER}"*/cover.webp)

magick $INPUT \
-fill '#00FF00' \
-stroke black \
-strokewidth 3 \
-gravity center \
-font TeXGyreHeros-Regular \
-pointsize 100 \
-annotate +0-300 "Episode ${EPISODE_NUMBER}" \
-font TeXGyreHeros-Italic \
-pointsize 160 \
-annotate +0+220 "${MOVIE_TITLE}" \
"${OUTPUT_FILE}"
